modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="dbm"
version="1.3"
displayName="Dragon Ball Mineverse"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dragon-ball-mineverse"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Rikudo_Sage"
description="The Best Dragon Ball Mod on the latest version of Minecraft"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.dbm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.dbm]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dbm]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration