
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.dbm.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.extensions.IForgeMenuType;

import net.minecraft.world.inventory.MenuType;

import net.mcreator.dbm.world.inventory.WelcomeGUIMenu;
import net.mcreator.dbm.world.inventory.StoryGUIMenu;
import net.mcreator.dbm.world.inventory.StoryGUI9Menu;
import net.mcreator.dbm.world.inventory.StoryGUI8Menu;
import net.mcreator.dbm.world.inventory.StoryGUI7Menu;
import net.mcreator.dbm.world.inventory.StoryGUI6Menu;
import net.mcreator.dbm.world.inventory.StoryGUI5Menu;
import net.mcreator.dbm.world.inventory.StoryGUI51Menu;
import net.mcreator.dbm.world.inventory.StoryGUI50Menu;
import net.mcreator.dbm.world.inventory.StoryGUI4Menu;
import net.mcreator.dbm.world.inventory.StoryGUI49Menu;
import net.mcreator.dbm.world.inventory.StoryGUI48Menu;
import net.mcreator.dbm.world.inventory.StoryGUI47Menu;
import net.mcreator.dbm.world.inventory.StoryGUI46Menu;
import net.mcreator.dbm.world.inventory.StoryGUI45Menu;
import net.mcreator.dbm.world.inventory.StoryGUI44Menu;
import net.mcreator.dbm.world.inventory.StoryGUI43Menu;
import net.mcreator.dbm.world.inventory.StoryGUI42Menu;
import net.mcreator.dbm.world.inventory.StoryGUI41Menu;
import net.mcreator.dbm.world.inventory.StoryGUI40Menu;
import net.mcreator.dbm.world.inventory.StoryGUI3Menu;
import net.mcreator.dbm.world.inventory.StoryGUI39Menu;
import net.mcreator.dbm.world.inventory.StoryGUI38Menu;
import net.mcreator.dbm.world.inventory.StoryGUI37Menu;
import net.mcreator.dbm.world.inventory.StoryGUI36Menu;
import net.mcreator.dbm.world.inventory.StoryGUI35Menu;
import net.mcreator.dbm.world.inventory.StoryGUI34Menu;
import net.mcreator.dbm.world.inventory.StoryGUI33Menu;
import net.mcreator.dbm.world.inventory.StoryGUI32Menu;
import net.mcreator.dbm.world.inventory.StoryGUI31Menu;
import net.mcreator.dbm.world.inventory.StoryGUI30Menu;
import net.mcreator.dbm.world.inventory.StoryGUI2Menu;
import net.mcreator.dbm.world.inventory.StoryGUI29Menu;
import net.mcreator.dbm.world.inventory.StoryGUI28Menu;
import net.mcreator.dbm.world.inventory.StoryGUI27Menu;
import net.mcreator.dbm.world.inventory.StoryGUI26Menu;
import net.mcreator.dbm.world.inventory.StoryGUI25Menu;
import net.mcreator.dbm.world.inventory.StoryGUI24Menu;
import net.mcreator.dbm.world.inventory.StoryGUI23Menu;
import net.mcreator.dbm.world.inventory.StoryGUI22Menu;
import net.mcreator.dbm.world.inventory.StoryGUI21Menu;
import net.mcreator.dbm.world.inventory.StoryGUI20Menu;
import net.mcreator.dbm.world.inventory.StoryGUI1Menu;
import net.mcreator.dbm.world.inventory.StoryGUI19Menu;
import net.mcreator.dbm.world.inventory.StoryGUI18Menu;
import net.mcreator.dbm.world.inventory.StoryGUI17Menu;
import net.mcreator.dbm.world.inventory.StoryGUI16Menu;
import net.mcreator.dbm.world.inventory.StoryGUI15Menu;
import net.mcreator.dbm.world.inventory.StoryGUI14Menu;
import net.mcreator.dbm.world.inventory.StoryGUI13Menu;
import net.mcreator.dbm.world.inventory.StoryGUI12Menu;
import net.mcreator.dbm.world.inventory.StoryGUI11Menu;
import net.mcreator.dbm.world.inventory.StoryGUI10Menu;
import net.mcreator.dbm.world.inventory.StatisticGUIMenu;
import net.mcreator.dbm.world.inventory.SkillsGUIMenu;
import net.mcreator.dbm.world.inventory.ShenronGUIMenu;
import net.mcreator.dbm.world.inventory.ShenronAgeGUIMenu;
import net.mcreator.dbm.world.inventory.SaiyanFormsGUIMenu;
import net.mcreator.dbm.world.inventory.PiccoloGUIMenu;
import net.mcreator.dbm.world.inventory.PiccoloGUI2Menu;
import net.mcreator.dbm.world.inventory.NorthKaioGUIMenu;
import net.mcreator.dbm.world.inventory.NorthKaioGUI2Menu;
import net.mcreator.dbm.world.inventory.KorinGUIMenu;
import net.mcreator.dbm.world.inventory.KorinDrinkGUIMenu;
import net.mcreator.dbm.world.inventory.KiAttacksGUIMenu;
import net.mcreator.dbm.world.inventory.KameSenninGUIMenu;
import net.mcreator.dbm.world.inventory.KameSenninGUI2Menu;
import net.mcreator.dbm.world.inventory.HalfSaiyanFormsGUIMenu;
import net.mcreator.dbm.world.inventory.GroupGUIMenu;
import net.mcreator.dbm.world.inventory.GroupGUI2Menu;
import net.mcreator.dbm.world.inventory.FinishGUIMenu;
import net.mcreator.dbm.world.inventory.EnmaGUIMenu;
import net.mcreator.dbm.world.inventory.DendeGUIMenu;
import net.mcreator.dbm.world.inventory.CharacterCreationGUIMenu;
import net.mcreator.dbm.world.inventory.CharacterCreationGUI2Menu;
import net.mcreator.dbm.world.inventory.ArcosianFormsGUIMenu;
import net.mcreator.dbm.DbmMod;

public class DbmModMenus {
	public static final DeferredRegister<MenuType<?>> REGISTRY = DeferredRegister.create(ForgeRegistries.MENU_TYPES, DbmMod.MODID);
	public static final RegistryObject<MenuType<WelcomeGUIMenu>> WELCOME_GUI = REGISTRY.register("welcome_gui", () -> IForgeMenuType.create(WelcomeGUIMenu::new));
	public static final RegistryObject<MenuType<CharacterCreationGUIMenu>> CHARACTER_CREATION_GUI = REGISTRY.register("character_creation_gui", () -> IForgeMenuType.create(CharacterCreationGUIMenu::new));
	public static final RegistryObject<MenuType<CharacterCreationGUI2Menu>> CHARACTER_CREATION_GUI_2 = REGISTRY.register("character_creation_gui_2", () -> IForgeMenuType.create(CharacterCreationGUI2Menu::new));
	public static final RegistryObject<MenuType<FinishGUIMenu>> FINISH_GUI = REGISTRY.register("finish_gui", () -> IForgeMenuType.create(FinishGUIMenu::new));
	public static final RegistryObject<MenuType<StatisticGUIMenu>> STATISTIC_GUI = REGISTRY.register("statistic_gui", () -> IForgeMenuType.create(StatisticGUIMenu::new));
	public static final RegistryObject<MenuType<SkillsGUIMenu>> SKILLS_GUI = REGISTRY.register("skills_gui", () -> IForgeMenuType.create(SkillsGUIMenu::new));
	public static final RegistryObject<MenuType<EnmaGUIMenu>> ENMA_GUI = REGISTRY.register("enma_gui", () -> IForgeMenuType.create(EnmaGUIMenu::new));
	public static final RegistryObject<MenuType<NorthKaioGUIMenu>> NORTH_KAIO_GUI = REGISTRY.register("north_kaio_gui", () -> IForgeMenuType.create(NorthKaioGUIMenu::new));
	public static final RegistryObject<MenuType<SaiyanFormsGUIMenu>> SAIYAN_FORMS_GUI = REGISTRY.register("saiyan_forms_gui", () -> IForgeMenuType.create(SaiyanFormsGUIMenu::new));
	public static final RegistryObject<MenuType<NorthKaioGUI2Menu>> NORTH_KAIO_GUI_2 = REGISTRY.register("north_kaio_gui_2", () -> IForgeMenuType.create(NorthKaioGUI2Menu::new));
	public static final RegistryObject<MenuType<KorinGUIMenu>> KORIN_GUI = REGISTRY.register("korin_gui", () -> IForgeMenuType.create(KorinGUIMenu::new));
	public static final RegistryObject<MenuType<DendeGUIMenu>> DENDE_GUI = REGISTRY.register("dende_gui", () -> IForgeMenuType.create(DendeGUIMenu::new));
	public static final RegistryObject<MenuType<KorinDrinkGUIMenu>> KORIN_DRINK_GUI = REGISTRY.register("korin_drink_gui", () -> IForgeMenuType.create(KorinDrinkGUIMenu::new));
	public static final RegistryObject<MenuType<KameSenninGUIMenu>> KAME_SENNIN_GUI = REGISTRY.register("kame_sennin_gui", () -> IForgeMenuType.create(KameSenninGUIMenu::new));
	public static final RegistryObject<MenuType<KameSenninGUI2Menu>> KAME_SENNIN_GUI_2 = REGISTRY.register("kame_sennin_gui_2", () -> IForgeMenuType.create(KameSenninGUI2Menu::new));
	public static final RegistryObject<MenuType<StoryGUIMenu>> STORY_GUI = REGISTRY.register("story_gui", () -> IForgeMenuType.create(StoryGUIMenu::new));
	public static final RegistryObject<MenuType<KiAttacksGUIMenu>> KI_ATTACKS_GUI = REGISTRY.register("ki_attacks_gui", () -> IForgeMenuType.create(KiAttacksGUIMenu::new));
	public static final RegistryObject<MenuType<ShenronGUIMenu>> SHENRON_GUI = REGISTRY.register("shenron_gui", () -> IForgeMenuType.create(ShenronGUIMenu::new));
	public static final RegistryObject<MenuType<ShenronAgeGUIMenu>> SHENRON_AGE_GUI = REGISTRY.register("shenron_age_gui", () -> IForgeMenuType.create(ShenronAgeGUIMenu::new));
	public static final RegistryObject<MenuType<StoryGUI1Menu>> STORY_GUI_1 = REGISTRY.register("story_gui_1", () -> IForgeMenuType.create(StoryGUI1Menu::new));
	public static final RegistryObject<MenuType<StoryGUI2Menu>> STORY_GUI_2 = REGISTRY.register("story_gui_2", () -> IForgeMenuType.create(StoryGUI2Menu::new));
	public static final RegistryObject<MenuType<StoryGUI3Menu>> STORY_GUI_3 = REGISTRY.register("story_gui_3", () -> IForgeMenuType.create(StoryGUI3Menu::new));
	public static final RegistryObject<MenuType<StoryGUI4Menu>> STORY_GUI_4 = REGISTRY.register("story_gui_4", () -> IForgeMenuType.create(StoryGUI4Menu::new));
	public static final RegistryObject<MenuType<ArcosianFormsGUIMenu>> ARCOSIAN_FORMS_GUI = REGISTRY.register("arcosian_forms_gui", () -> IForgeMenuType.create(ArcosianFormsGUIMenu::new));
	public static final RegistryObject<MenuType<HalfSaiyanFormsGUIMenu>> HALF_SAIYAN_FORMS_GUI = REGISTRY.register("half_saiyan_forms_gui", () -> IForgeMenuType.create(HalfSaiyanFormsGUIMenu::new));
	public static final RegistryObject<MenuType<StoryGUI5Menu>> STORY_GUI_5 = REGISTRY.register("story_gui_5", () -> IForgeMenuType.create(StoryGUI5Menu::new));
	public static final RegistryObject<MenuType<StoryGUI6Menu>> STORY_GUI_6 = REGISTRY.register("story_gui_6", () -> IForgeMenuType.create(StoryGUI6Menu::new));
	public static final RegistryObject<MenuType<PiccoloGUIMenu>> PICCOLO_GUI = REGISTRY.register("piccolo_gui", () -> IForgeMenuType.create(PiccoloGUIMenu::new));
	public static final RegistryObject<MenuType<PiccoloGUI2Menu>> PICCOLO_GUI_2 = REGISTRY.register("piccolo_gui_2", () -> IForgeMenuType.create(PiccoloGUI2Menu::new));
	public static final RegistryObject<MenuType<StoryGUI7Menu>> STORY_GUI_7 = REGISTRY.register("story_gui_7", () -> IForgeMenuType.create(StoryGUI7Menu::new));
	public static final RegistryObject<MenuType<StoryGUI8Menu>> STORY_GUI_8 = REGISTRY.register("story_gui_8", () -> IForgeMenuType.create(StoryGUI8Menu::new));
	public static final RegistryObject<MenuType<StoryGUI9Menu>> STORY_GUI_9 = REGISTRY.register("story_gui_9", () -> IForgeMenuType.create(StoryGUI9Menu::new));
	public static final RegistryObject<MenuType<StoryGUI10Menu>> STORY_GUI_10 = REGISTRY.register("story_gui_10", () -> IForgeMenuType.create(StoryGUI10Menu::new));
	public static final RegistryObject<MenuType<StoryGUI11Menu>> STORY_GUI_11 = REGISTRY.register("story_gui_11", () -> IForgeMenuType.create(StoryGUI11Menu::new));
	public static final RegistryObject<MenuType<StoryGUI12Menu>> STORY_GUI_12 = REGISTRY.register("story_gui_12", () -> IForgeMenuType.create(StoryGUI12Menu::new));
	public static final RegistryObject<MenuType<StoryGUI13Menu>> STORY_GUI_13 = REGISTRY.register("story_gui_13", () -> IForgeMenuType.create(StoryGUI13Menu::new));
	public static final RegistryObject<MenuType<StoryGUI14Menu>> STORY_GUI_14 = REGISTRY.register("story_gui_14", () -> IForgeMenuType.create(StoryGUI14Menu::new));
	public static final RegistryObject<MenuType<StoryGUI15Menu>> STORY_GUI_15 = REGISTRY.register("story_gui_15", () -> IForgeMenuType.create(StoryGUI15Menu::new));
	public static final RegistryObject<MenuType<StoryGUI16Menu>> STORY_GUI_16 = REGISTRY.register("story_gui_16", () -> IForgeMenuType.create(StoryGUI16Menu::new));
	public static final RegistryObject<MenuType<StoryGUI17Menu>> STORY_GUI_17 = REGISTRY.register("story_gui_17", () -> IForgeMenuType.create(StoryGUI17Menu::new));
	public static final RegistryObject<MenuType<StoryGUI18Menu>> STORY_GUI_18 = REGISTRY.register("story_gui_18", () -> IForgeMenuType.create(StoryGUI18Menu::new));
	public static final RegistryObject<MenuType<StoryGUI19Menu>> STORY_GUI_19 = REGISTRY.register("story_gui_19", () -> IForgeMenuType.create(StoryGUI19Menu::new));
	public static final RegistryObject<MenuType<GroupGUIMenu>> GROUP_GUI = REGISTRY.register("group_gui", () -> IForgeMenuType.create(GroupGUIMenu::new));
	public static final RegistryObject<MenuType<GroupGUI2Menu>> GROUP_GUI_2 = REGISTRY.register("group_gui_2", () -> IForgeMenuType.create(GroupGUI2Menu::new));
	public static final RegistryObject<MenuType<StoryGUI20Menu>> STORY_GUI_20 = REGISTRY.register("story_gui_20", () -> IForgeMenuType.create(StoryGUI20Menu::new));
	public static final RegistryObject<MenuType<StoryGUI21Menu>> STORY_GUI_21 = REGISTRY.register("story_gui_21", () -> IForgeMenuType.create(StoryGUI21Menu::new));
	public static final RegistryObject<MenuType<StoryGUI22Menu>> STORY_GUI_22 = REGISTRY.register("story_gui_22", () -> IForgeMenuType.create(StoryGUI22Menu::new));
	public static final RegistryObject<MenuType<StoryGUI23Menu>> STORY_GUI_23 = REGISTRY.register("story_gui_23", () -> IForgeMenuType.create(StoryGUI23Menu::new));
	public static final RegistryObject<MenuType<StoryGUI24Menu>> STORY_GUI_24 = REGISTRY.register("story_gui_24", () -> IForgeMenuType.create(StoryGUI24Menu::new));
	public static final RegistryObject<MenuType<StoryGUI25Menu>> STORY_GUI_25 = REGISTRY.register("story_gui_25", () -> IForgeMenuType.create(StoryGUI25Menu::new));
	public static final RegistryObject<MenuType<StoryGUI26Menu>> STORY_GUI_26 = REGISTRY.register("story_gui_26", () -> IForgeMenuType.create(StoryGUI26Menu::new));
	public static final RegistryObject<MenuType<StoryGUI27Menu>> STORY_GUI_27 = REGISTRY.register("story_gui_27", () -> IForgeMenuType.create(StoryGUI27Menu::new));
	public static final RegistryObject<MenuType<StoryGUI28Menu>> STORY_GUI_28 = REGISTRY.register("story_gui_28", () -> IForgeMenuType.create(StoryGUI28Menu::new));
	public static final RegistryObject<MenuType<StoryGUI29Menu>> STORY_GUI_29 = REGISTRY.register("story_gui_29", () -> IForgeMenuType.create(StoryGUI29Menu::new));
	public static final RegistryObject<MenuType<StoryGUI30Menu>> STORY_GUI_30 = REGISTRY.register("story_gui_30", () -> IForgeMenuType.create(StoryGUI30Menu::new));
	public static final RegistryObject<MenuType<StoryGUI31Menu>> STORY_GUI_31 = REGISTRY.register("story_gui_31", () -> IForgeMenuType.create(StoryGUI31Menu::new));
	public static final RegistryObject<MenuType<StoryGUI32Menu>> STORY_GUI_32 = REGISTRY.register("story_gui_32", () -> IForgeMenuType.create(StoryGUI32Menu::new));
	public static final RegistryObject<MenuType<StoryGUI33Menu>> STORY_GUI_33 = REGISTRY.register("story_gui_33", () -> IForgeMenuType.create(StoryGUI33Menu::new));
	public static final RegistryObject<MenuType<StoryGUI34Menu>> STORY_GUI_34 = REGISTRY.register("story_gui_34", () -> IForgeMenuType.create(StoryGUI34Menu::new));
	public static final RegistryObject<MenuType<StoryGUI35Menu>> STORY_GUI_35 = REGISTRY.register("story_gui_35", () -> IForgeMenuType.create(StoryGUI35Menu::new));
	public static final RegistryObject<MenuType<StoryGUI36Menu>> STORY_GUI_36 = REGISTRY.register("story_gui_36", () -> IForgeMenuType.create(StoryGUI36Menu::new));
	public static final RegistryObject<MenuType<StoryGUI37Menu>> STORY_GUI_37 = REGISTRY.register("story_gui_37", () -> IForgeMenuType.create(StoryGUI37Menu::new));
	public static final RegistryObject<MenuType<StoryGUI38Menu>> STORY_GUI_38 = REGISTRY.register("story_gui_38", () -> IForgeMenuType.create(StoryGUI38Menu::new));
	public static final RegistryObject<MenuType<StoryGUI39Menu>> STORY_GUI_39 = REGISTRY.register("story_gui_39", () -> IForgeMenuType.create(StoryGUI39Menu::new));
	public static final RegistryObject<MenuType<StoryGUI40Menu>> STORY_GUI_40 = REGISTRY.register("story_gui_40", () -> IForgeMenuType.create(StoryGUI40Menu::new));
	public static final RegistryObject<MenuType<StoryGUI41Menu>> STORY_GUI_41 = REGISTRY.register("story_gui_41", () -> IForgeMenuType.create(StoryGUI41Menu::new));
	public static final RegistryObject<MenuType<StoryGUI42Menu>> STORY_GUI_42 = REGISTRY.register("story_gui_42", () -> IForgeMenuType.create(StoryGUI42Menu::new));
	public static final RegistryObject<MenuType<StoryGUI43Menu>> STORY_GUI_43 = REGISTRY.register("story_gui_43", () -> IForgeMenuType.create(StoryGUI43Menu::new));
	public static final RegistryObject<MenuType<StoryGUI44Menu>> STORY_GUI_44 = REGISTRY.register("story_gui_44", () -> IForgeMenuType.create(StoryGUI44Menu::new));
	public static final RegistryObject<MenuType<StoryGUI45Menu>> STORY_GUI_45 = REGISTRY.register("story_gui_45", () -> IForgeMenuType.create(StoryGUI45Menu::new));
	public static final RegistryObject<MenuType<StoryGUI46Menu>> STORY_GUI_46 = REGISTRY.register("story_gui_46", () -> IForgeMenuType.create(StoryGUI46Menu::new));
	public static final RegistryObject<MenuType<StoryGUI47Menu>> STORY_GUI_47 = REGISTRY.register("story_gui_47", () -> IForgeMenuType.create(StoryGUI47Menu::new));
	public static final RegistryObject<MenuType<StoryGUI48Menu>> STORY_GUI_48 = REGISTRY.register("story_gui_48", () -> IForgeMenuType.create(StoryGUI48Menu::new));
	public static final RegistryObject<MenuType<StoryGUI49Menu>> STORY_GUI_49 = REGISTRY.register("story_gui_49", () -> IForgeMenuType.create(StoryGUI49Menu::new));
	public static final RegistryObject<MenuType<StoryGUI50Menu>> STORY_GUI_50 = REGISTRY.register("story_gui_50", () -> IForgeMenuType.create(StoryGUI50Menu::new));
	public static final RegistryObject<MenuType<StoryGUI51Menu>> STORY_GUI_51 = REGISTRY.register("story_gui_51", () -> IForgeMenuType.create(StoryGUI51Menu::new));
}
